### ISSUE TITLE
Assets cannot be withdrawn on Abra Finance

### ISSUE THREAD

**Issue by tuongkcv** [morph-l2/morph#367]
After providing tokens on Abra Finance, I cannot withdraw my assets. Error reported on attached image. Please send this report to the development team to fix
<img width="1507" alt="Screen Shot 2024-06-08 at 13 00 17" src="https://github.com/morph-l2/morph/assets/94736603/75aa6902-b23d-4450-94f5-77bdecfcfcaa">

**Comment by pclaesen** [comment]
@tuongkcv There's very low liquidity in the pool most of the time. This is not a technical error afaik, just the way how pools work.

**Comment by chengwenxi** [comment]
Yes, this is not a technical error.
