### ISSUE TITLE
What root does `finalizedStateRoots()` correspond to?

### ISSUE THREAD

**Issue by adraffy** [morph-l2/morph#640]
`finalizedStateRoots()` doesn't match the end block of a batch (or anything I've tested), which means `eth_getProof` cannot be verified from the finalized rollup state.

`finalizedStateRoots(1932)` = `0x001b0f9bcf86e28bfdde95786a24c920339317fb656e0981417d444be8cb73d1`

https://explorer.morphl2.io/batches/1932 &rarr; `[532550, 532849]` (300 blocks)

`eth_getBlockByNumber(532849).stateRoot` = `0x02d2e587068002b7201bbc94863f66a6090abc5f5203edf4da0dc35b8df19769`

The block `stateRoot` is a poseidon hash and verifies `eth_getProof` correctly.

`0x001b...` =!= `0x02d2...`

**Comment by FletcherMan** [comment]
you might get the wrong stateRoot of block `532849`, please try 
```
curl --location 'https://rpc.morphl2.io' \
--header 'Content-Type: application/json' \
--data '{
        "jsonrpc":"2.0",
        "method":"eth_getBlockByNumber",
        "params":[
                "0x82171",
                true
        ],
        "id":1
}'
```

And the returned `stateRoot` is `0x001b0f9bcf86e28bfdde95786a24c920339317fb656e0981417d444be8cb73d1`

**Comment by FletcherMan** [comment]
> `finalizedStateRoots()` doesn't match the end block of a batch (or anything I've tested), which means `eth_getProof` cannot be verified from the finalized rollup state.
> 
> `finalizedStateRoots(1932)` = `0x001b0f9bcf86e28bfdde95786a24c920339317fb656e0981417d444be8cb73d1`
> 
> https://explorer.morphl2.io/batches/1932 → `[532550, 532849]` (300 blocks)
> 
> `eth_getBlockByNumber(532849).stateRoot` = `0x02d2e587068002b7201bbc94863f66a6090abc5f5203edf4da0dc35b8df19769`
> 
> The block `stateRoot` is a poseidon hash and verifies `eth_getProof` correctly.
> 
> `0x001b...` =!= `0x02d2...`

you might get the wrong stateRoot of block 532849, please try

```
curl --location 'https://rpc.morphl2.io' \
--header 'Content-Type: application/json' \
--data '{
        "jsonrpc":"2.0",
        "method":"eth_getBlockByNumber",
        "params":[
                "0x82171",
                true
        ],
        "id":1
}'
```
And the returned `stateRoot` is `0x001b0f9bcf86e28bfdde95786a24c920339317fb656e0981417d444be8cb73d1`
